import { FormControl } from '@angular/forms';

export interface LoginForm {
  email: FormControl<string | null>;
  password: FormControl<string | null>;
}
// Generated by https://quicktype.io

export interface CenterResponse {
  documents: Document[];
}

export interface Document {
  name: string;
  fields: Fields;
  createTime: string;
  updateTime: string;
}

export interface Fields {
  centerName: CenterName;
}

export interface CenterName {
  stringValue: string;
}
